-- OBJECTIVE
-- 1.CREATE A DETAIL INFORMATION AND CREAT A CLASS EACH INSURER BASE ON BMI AND AGE GROUP?
-- 2.WHAT ARE THE AVG_CHARGES AND AVG_BMI BASED ON AGE GROUP?
-- 3.WHAT ARE THE AVG_CHARGES AS PER GENDER BASED ON SMOKING AND BMI GROUP?
-- 4.WHAT ARE THE DATA OF AVG_CHARGES BASED ON BMI AND GENDER IN AGE_GROUP BETWEEN (18 TO 30) (31 TO 40) (41 TO 50) AND (51 TO 65)?
-- 5.WHAR IS THE REGION WISE AVG_CHARGES BASED ON GENDER?
-- 6.CREATE A GENDER SEGMENTATION BY WEIGHT_CLASS AND OVERALL AVG_CHARGES
-- 7.WHAT ARE THE PERCENTAGE OF GENDER PAYING MORE THEN AVG_CHARGES 
-- 8 WHAT ARE THE PERCENTAGE OF GENDER PAYING MORE THEN AVG_CHARGES OF MALE AND FEMALE CONSIDERING SMOKING FACTORS
-- 9.CREATE PROCEDURE FOR FINDING REGION WISE DATA ON AVG_CHARGES BASE ON GENDER
-- 10.CREATE PROCEDURE FOR FINDING DATA BASE ON BMI GROUP (UNDER_WEIGHT, NORMAL_WEIGHT, OVER_WEIGHT, OBESITY AND MORBID_OBESITY)
-- 11.CREATE PROCEDURE FOR FIDING DATA BASE ON INPUT OF GENDER, BMI_GROUP


--  DETAIL INFORMATION OF EACH INSURER
WITH CTE_TOTAL_AVG_CHARGES AS(
SELECT 
      CONCAT('$',ROUND(AVG(CHARGES),2)) AS AVG_CHARGES
FROM INSURANCE
)
SELECT 
      AGE,
      CASE
      WHEN AGE BETWEEN 18 AND 30 THEN '18-30'
      WHEN AGE BETWEEN 31 AND 40 THEN '31-40'
      WHEN AGE BETWEEN 41 AND 50 THEN '41-50'
      WHEN AGE BETWEEN 51 AND 65 THEN '51-65'
      END AS AGE_GROUP,
      SEX,
      BMI,
      CASE 
      WHEN BMI < 18.5 THEN 'UNDER_WEIGHT'
      WHEN BMI BETWEEN 18.6 AND 24.9 THEN 'NORMAL_WEIGHT'
      WHEN BMI BETWEEN 25 AND 29.9 THEN 'OVER_WEIGHT'
      WHEN BMI BETWEEN 30 AND 39.9 THEN 'OBESITY'
      WHEN BMI > 40 THEN 'MORBID_OBESITY'
      END AS BMI_GROUP,
      CHILDREN,
      SMOKER,
      REGION,
      CONCAT('$',ROUND(CHARGES,2)) AS CHARGES,
      AVG_CHARGES,
      CONCAT(ROUND((CHARGES - 13270.42) / 13270.42   * 100,2),'%') AS ABOVE_AVG_PAID,
      DENSE_RANK () OVER (PARTITION BY AGE ORDER BY CHARGES) AS RANK_NUM_PER_CHARGES
FROM INSURANCE 
JOIN CTE_TOTAL_AVG_CHARGES;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- AVG_CHARGES AND AVG_BMI BASED ON AGE GROUP

SELECT 
      DISTINCT(SEX),
      '18-30' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(BMI),2) AS AVG_BMI,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES
FROM INSURANCE 
WHERE AGE BETWEEN 18 AND 30
GROUP BY SEX
UNION
SELECT 
      DISTINCT(SEX),
      '31-40' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(BMI),2) AS AVG_BMI,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES
FROM INSURANCE 
WHERE AGE BETWEEN 31 AND 40
GROUP BY SEX
UNION
SELECT 
      DISTINCT(SEX),
      '41-50' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(BMI),2) AS AVG_BMI,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES
FROM INSURANCE 
WHERE AGE BETWEEN 41 AND 50
GROUP BY SEX
UNION
SELECT 
      DISTINCT(SEX),
      '51-64' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(BMI),2) AS AVG_BMI,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES
FROM INSURANCE 
WHERE AGE BETWEEN 51 AND 64
GROUP BY SEX;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- AVG_CHARGES AS PER GENDER BASED ON SMOKING AND BMI GROUP

SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'UNDER_WEIGHT' AS BMI_GROUP,
      COUNT(AGE),
      AVG(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI < 18.5
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'NORMAL_WEIGHT' AS BMI_GROUP,
      COUNT(AGE),
      AVG(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 18.6 AND 24.9
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OVER_WEIGHT' AS BMI_GROUP,
      COUNT(AGE),
      AVG(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 25 AND 29.9
GROUP BY SMOKER, SEX 
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OBESITY' AS BMI_GROUP,
      COUNT(AGE),
      AVG(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 30 AND 39.9
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'MORBID_OBESITY' AS BMI_GROUP,
      COUNT(AGE),
      AVG(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI > 40
GROUP BY SMOKER, SEX;
----------------------------------------------------------------------------------
 -- DATA OF AVG_CHARGES BASED ON BMI AND GENDER IN AGE_GROUP BETWEEN 18 TO 30 
 
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      REGION,
      'UNDER_WEIGHT' AS BMI_GROUP,
      '18-30' AS AGE_GROUP,
      COUNT(AGE) AS POPULATION,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      DENSE_RANK () OVER (PARTITION BY SMOKER ORDER BY AVG(CHARGES) DESC) AS RANK_NUM
FROM INSURANCE 
WHERE BMI < 18.5 AND AGE BETWEEN 18 AND 30
GROUP BY SMOKER,SEX,REGION
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      REGION,
      'NORMAL_WEIGHT' AS BMI_GROUP,
      '18-30' AS AGE_GROUP,
      COUNT(AGE) AS POPULATION,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
        DENSE_RANK () OVER (PARTITION BY SMOKER ORDER BY AVG(CHARGES) DESC) AS RANK_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 18.6 AND 24.9 AND AGE BETWEEN 18 AND 30
GROUP BY SMOKER,SEX,REGION
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      REGION,
      'OVER_WEIGHT' AS BMI_GROUP,
      '18-30' AS AGE_GROUP,
      COUNT(AGE) AS POPULATION,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
        DENSE_RANK () OVER (PARTITION BY SMOKER ORDER BY AVG(CHARGES) DESC) AS RANK_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 25 AND 29.9 AND AGE BETWEEN 18 AND 30
GROUP BY SMOKER, SEX,REGION
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      REGION,
      'OBESITY' AS BMI_GROUP,
      '18-30' AS  AGE_GROUP,
      COUNT(AGE) AS POPULATION,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
        DENSE_RANK () OVER (PARTITION BY SMOKER ORDER BY AVG(CHARGES) DESC) AS RANK_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 30 AND 39.9 AND AGE BETWEEN 18 AND 30
GROUP BY SMOKER, SEX,REGION
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      REGION,
      'MORBID_OBESITY' AS BMI_GROUP,
      '18-30' AS AGE_GROUP,
      COUNT(AGE) AS POPULATION,
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
        DENSE_RANK () OVER (PARTITION BY SMOKER ORDER BY AVG(CHARGES) DESC) AS RANK_NUM
FROM INSURANCE 
WHERE BMI > 40 AND AGE BETWEEN 18 AND 30
GROUP BY SMOKER, SEX,REGION;

-------------------------------------------------------------------------------------------------- 
-- DATA OF AVG_CHARGES BASED ON BMI AND GENDER IN AGE_GROUP BETWEEN 31 TO 40 

SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'UNDER_WEIGHT' AS BMI_GROUP,
      '31-40' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI < 18.5 AND AGE BETWEEN 31 AND 40
GROUP BY SMOKER,SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'NORMAL_WEIGHT' AS BMI_GROUP,
      '31-40' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 18.6 AND 24.9 AND AGE BETWEEN 31 AND 40
GROUP BY SMOKER,SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OVER_WEIGHT' AS BMI_GROUP,
      '31-40' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 25 AND 29.9 AND AGE BETWEEN 31 AND 40
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OBESITY' AS BMI_GROUP,
      '31-40' AS  AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 30 AND 39.9 AND AGE BETWEEN 31 AND 40
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'MORBID_OBESITY' AS BMI_GROUP,
      '31-40' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI > 40 AND AGE BETWEEN 31 AND 40
GROUP BY SMOKER, SEX;

------------------------------------------------------------------------------------------
-- DATA OF AVG_CHARGES BASED ON BMI AND GENDER IN AGE_GROUP BETWEEN 41 TO 50 

SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'UNDER_WEIGHT' AS BMI_GROUP,
      '41-50' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI < 18.5 AND AGE BETWEEN 41 AND 50
GROUP BY SMOKER,SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'NORMAL_WEIGHT' AS BMI_GROUP,
      '41-50' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 18.6 AND 24.9 AND AGE BETWEEN 41 AND 50
GROUP BY SMOKER,SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OVER_WEIGHT' AS BMI_GROUP,
      '41-50' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 25 AND 29.9 AND AGE BETWEEN 41 AND 50
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OBESITY' AS BMI_GROUP,
      '41-50' AS  AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 30 AND 39.9 AND AGE BETWEEN 41 AND 50
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'MORBID_OBESITY' AS BMI_GROUP,
      '41-50' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI > 40 AND AGE BETWEEN 41 AND 50
GROUP BY SMOKER, SEX;

---------------------------------------------------------------------------------------------
-- DATA OF AVG_CHARGES BASED ON BMI AND GENDER IN AGE_GROUP BETWEEN 51 TO 64 

SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'UNDER_WEIGHT' AS BMI_GROUP,
      '51-64' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI < 18.5 AND AGE BETWEEN 51 AND 64
GROUP BY SMOKER,SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'NORMAL_WEIGHT' AS BMI_GROUP,
      '51-64' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 18.6 AND 24.9 AND AGE BETWEEN 51 AND 64
GROUP BY SMOKER,SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OVER_WEIGHT' AS BMI_GROUP,
      '51-64' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 25 AND 29.9 AND AGE BETWEEN 51 AND 64
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'OBESITY' AS BMI_GROUP,
      '51-64' AS  AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI BETWEEN 30 AND 39.9 AND AGE BETWEEN 51 AND 64
GROUP BY SMOKER, SEX
UNION
SELECT
      DISTINCT(SMOKER),
      SEX AS GENDER,
      'MORBID_OBESITY' AS BMI_GROUP,
      '51-64' AS AGE_GROUP,
      COUNT(AGE),
      ROUND(AVG(CHARGES), 2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY SMOKER) AS ROW_NUM
FROM INSURANCE 
WHERE BMI > 40 AND AGE BETWEEN 51 AND 64
GROUP BY SMOKER, SEX;

-----------------------------------------------------------------------------------------------------------------------------------------
-- REGION WISE AVG_CHARGES BASED ON GENDER 

SELECT 
      DISTINCT(SMOKER) AS SMOKERS,
      REGION AS REGIONS,
      SEX AS GENDERS,
      'UNDER_WEIGTH' AS WEIGHT,
      COUNT(BMI) POPULATION,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI < 18.5 
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER),
      REGION,
      SEX AS GENDER,
      'NORMAL_WEIGHT' AS WEIGHT,
      COUNT(BMI) AS POPULATION,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI BETWEEN 18.6 AND 24.9
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER) AS SMOKERS,
      REGION AS REGIONS,
      SEX AS GENDERS,
      'OVER_WEIGTH' AS WEIGHT,
      COUNT(BMI) POPULATION,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI BETWEEN 25 AND 29.9 
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER),
      REGION,
      SEX AS GENDER,
      'OBESITY' AS WEIGHT,
      COUNT(BMI) AS POPULATION,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI BETWEEN 30 AND 39.9
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER),
      REGION,
      SEX AS GENDER,
      'MORBID_OBESITY' AS WEIGHT,
      COUNT(BMI) AS POPULATION,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI > 40
GROUP BY SMOKER, REGION, SEX;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- GENDER SEGMENTATION BY WEIGHT_CLASS AND OVERALL AVG_CHARGES

SELECT 
	  DISTINCT(SEX),
      SMOKER,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES,
      SUM(CASE WHEN BMI < 18.5 THEN 1 ELSE 0 END) AS UNDER_WEIGHT,
      SUM(CASE WHEN BMI BETWEEN 18.5 AND 24.9 THEN 1 ELSE 0 END) AS NORMAL_WEIGHT,
      SUM(CASE WHEN BMI BETWEEN 25 AND 29.9 THEN 1 ELSE 0 END) AS OVER_WEIGHT,
      SUM(CASE WHEN BMI BETWEEN 30 AND 39.9 THEN 1 ELSE 0 END) AS OBESITY,
      SUM(CASE WHEN BMI > 40 THEN 1 ELSE 0 END) AS MORBID_OBESITY
FROM INSURANCE
GROUP BY SEX, SMOKER
ORDER BY SEX;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- PERCENTAGE OF GENDER PAYING MORE THEN AVG_CHARGES OF MALE AND FEMALE

WITH CTE_AVG_CHARGES AS (
SELECT 
      DISTINCT(SEX) AS GENDER,
      COUNT(SEX) AS NUM_PEOPLE,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES
FROM INSURANCE
WHERE SEX = 'FEMALE' 
GROUP BY SEX
),
CTE_CHARGES AS(
SELECT 
      CHARGES AS CHARGES
FROM INSURANCE
WHERE SEX = 'FEMALE'
)
SELECT 
      GENDER,
      NUM_PEOPLE,
      CONCAT('$',AVG_CHARGES) AS AVG_CHARGES,
      SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) AS HIGHER_THEN_AVG,
      CONCAT(ROUND(SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) / NUM_PEOPLE * 100,2),'%') AS ABOVE_PERCENTAGE
    
FROM CTE_AVG_CHARGES
JOIN CTE_CHARGES
GROUP BY GENDER
UNION
SELECT *
FROM (WITH CTE_AVG_CHARGES AS (
SELECT 
      DISTINCT(SEX) AS GENDER,
      COUNT(SEX) AS NUM_PEOPLE,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES
FROM INSURANCE
WHERE SEX = 'MALE' 
GROUP BY SEX
),
CTE_CHARGES AS(
SELECT 
      CHARGES AS CHARGES
FROM INSURANCE
WHERE SEX = 'MALE' 
)
SELECT 
      GENDER,
      NUM_PEOPLE,
      CONCAT('$',AVG_CHARGES) ,
      SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) AS HIGHER_THEN_AVG,
      CONCAT(ROUND(SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) / NUM_PEOPLE * 100,2),'%') AS ABOVE_PERCENTAGE
    
FROM CTE_AVG_CHARGES
JOIN CTE_CHARGES
GROUP BY GENDER) A


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- PERCENTAGE OF GENDER PAYING MORE THEN AVG_CHARGES OF MALE AND FEMALE CONSIDERING SMOKING FACTORS

WITH CTE_AVG_CHARGES AS (
SELECT 
      DISTINCT(SEX) AS GENDER,
      COUNT(SEX) AS NUM_PEOPLE,
      SMOKER AS SMOKERS,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES
FROM INSURANCE
WHERE SEX = 'FEMALE' AND SMOKER = 'YES'
GROUP BY SEX,SMOKERS
),
CTE_CHARGES AS(
SELECT 
      CHARGES AS CHARGES
FROM INSURANCE
WHERE SEX = 'FEMALE' AND SMOKER = 'YES'
)
SELECT 
      GENDER,
      NUM_PEOPLE,
      SMOKERS,
      CONCAT('$',AVG_CHARGES) AS AVG_CHARGES,
      SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) AS HIGHER_THEN_AVG,
      CONCAT(ROUND(SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) / NUM_PEOPLE * 100,2),'%') AS PERCENTAGE
FROM CTE_AVG_CHARGES
JOIN CTE_CHARGES
GROUP BY GENDER, SMOKERS, NUM_PEOPLE
UNION
SELECT *
FROM (WITH CTE_AVG_CHARGES AS (
SELECT 
      DISTINCT(SEX) AS GENDER,
      COUNT(SEX) AS NUM_PEOPLE,
      SMOKER AS SMOKERS,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES
FROM INSURANCE
WHERE SEX = 'MALE' AND SMOKER = 'YES'
GROUP BY SEX
),
CTE_CHARGES AS(
SELECT 
      CHARGES AS CHARGES
FROM INSURANCE
WHERE SEX = 'MALE' AND SMOKER = 'YES'
)
SELECT 
      GENDER,
      NUM_PEOPLE,
      SMOKERS,
      CONCAT('$',AVG_CHARGES),
      SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) AS HIGHER_THEN_AVG,
      CONCAT(ROUND(SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) / NUM_PEOPLE * 100,2),'%') AS PERCENTAGE
FROM CTE_AVG_CHARGES
JOIN CTE_CHARGES
GROUP BY GENDER,SMOKERS, NUM_PEOPLE) A
UNION
SELECT *
FROM (
WITH CTE_AVG_CHARGES AS (
SELECT 
      DISTINCT(SEX) AS GENDER,
      COUNT(SEX) AS NUM_PEOPLE,
      SMOKER AS SMOKERS,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES
FROM INSURANCE
WHERE SEX = 'FEMALE' AND SMOKER = 'NO'
GROUP BY SEX,SMOKERS
),
CTE_CHARGES AS(
SELECT 
      CHARGES AS CHARGES
FROM INSURANCE
WHERE SEX = 'FEMALE' AND SMOKER = 'NO'
)
SELECT 
      GENDER,
      NUM_PEOPLE,
      SMOKERS,
      CONCAT('$',AVG_CHARGES),
      SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) AS HIGHER_THEN_AVG,
      CONCAT(ROUND(SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) / NUM_PEOPLE * 100,2),'%') AS PERCENTAGE
    
FROM CTE_AVG_CHARGES
JOIN CTE_CHARGES
GROUP BY GENDER, SMOKERS, NUM_PEOPLE) B
UNION
SELECT *
FROM (WITH CTE_AVG_CHARGES AS (
SELECT 
      DISTINCT(SEX) AS GENDER,
      COUNT(SEX) AS NUM_PEOPLE,
      SMOKER AS SMOKERS,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES
FROM INSURANCE
WHERE SEX = 'MALE' AND SMOKER = 'NO'
GROUP BY SEX
),
CTE_CHARGES AS(
SELECT 
      CHARGES AS CHARGES
FROM INSURANCE
WHERE SEX = 'MALE' AND SMOKER = 'NO'
)
SELECT 
      GENDER,
      NUM_PEOPLE,
      SMOKERS,
      CONCAT('$',AVG_CHARGES),
      SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) AS HIGHER_THEN_AVG,
      CONCAT(ROUND(SUM(CASE WHEN CHARGES > AVG_CHARGES THEN 1 ELSE 0 END) / NUM_PEOPLE * 100,2),'%') AS PERCENTAGE
    
FROM CTE_AVG_CHARGES
JOIN CTE_CHARGES
GROUP BY GENDER,SMOKERS, NUM_PEOPLE) C

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- PROCEDURE TO FIND AVG_CHARGES BASE OF REGION ON GENDER AND SMOKING FACTOR
DELIMITER $$
CREATE PROCEDURE p_region_data (IN p_region VARCHAR(50))
BEGIN

SELECT 
      DISTINCT(SMOKER),
      REGION,
      SEX AS GENDER,
      COUNT(AGE) AS POPULATION,
      ROUND(AVG(CHARGES),2) AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE 
WHERE P_REGION = INSURANCE.REGION
GROUP BY SMOKER, REGION, SEX;

END $$
DELIMITER ;

--------------------------------------------------------------------------------------------------------------------
-- PROCEDURE FOR DETAIL SEARCH BASED ON WEIGHT CLASS, REGION AND GENDER

DELIMITER $$
CREATE PROCEDURE P_WEIGHT_CLASS_DETAIL_INFO (IN P_WEIGHT VARCHAR(50) , IN P_REGION VARCHAR(50), IN P_GENDER VARCHAR(50))
BEGIN
SELECT *
FROM (
SELECT 
      DISTINCT(SMOKER) AS SMOKERS,
      REGION AS REGIONS,
      SEX AS GENDER,
      'UNDER_WEIGHT' AS WEIGHT,
      COUNT(BMI) POPULATION,
      CONCAT(ROUND(AVG(CHARGES),2),'$') AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI < 18.5 
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER),
      REGION AS REGIONS,
      SEX AS GENDER,
      'NORMAL_WEIGHT' AS WEIGHT,
      COUNT(BMI) AS POPULATION,
      CONCAT(ROUND(AVG(CHARGES),2),'$') AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI BETWEEN 18.6 AND 24.9
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER) AS SMOKERS,
      REGION AS REGIONS,
      SEX AS GENDER,
      'OVER_WEIGHT' AS WEIGHT,
      COUNT(BMI) POPULATION,
      CONCAT(ROUND(AVG(CHARGES),2),'$') AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI BETWEEN 25 AND 29.9 
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER),
      REGION AS REGIONS,
      SEX AS GENDER,
      'OBESITY' AS WEIGHT,
      COUNT(BMI) AS POPULATION,
      CONCAT(ROUND(AVG(CHARGES),2),'$') AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE
WHERE BMI BETWEEN 30 AND 39.9
GROUP BY SMOKER, REGION, SEX
UNION
SELECT 
      DISTINCT(SMOKER),
      REGION AS REGIONS,
      SEX AS GENDER,
      'MORBID_OBESITY' AS WEIGHT,
      COUNT(BMI) AS POPULATION,
      CONCAT(ROUND(AVG(CHARGES),2),'$') AS AVG_CHARGES,
      ROW_NUMBER () OVER (PARTITION BY REGION) AS ROW_NUM
FROM INSURANCE 
WHERE BMI > 40 
GROUP BY SMOKER, REGION, SEX) I
WHERE P_WEIGHT = I.WEIGHT AND P_REGION = I.REGIONS AND P_GENDER = I.GENDER;
END $$
DELIMITER ;


